language: node_js
node_js:
  - "stable"
  - "7"
  - "6"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
  - echo "Hello"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build
  on:
    branch: master