language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  before_script:
  - npm run build
script:
  - npm test
  - npm run build
  - echo "test"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master