language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script:
  - npm run build
script:
  - npm test
  - npm run build
  - echo "test"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: dc0d38364dc1c56077231576fd9190e450d501f5
  local_dir: build
  on:
    branch: master